name: Terraform CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # Step 3: Initialize Terraform
      - name: Initialize Terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: terraform init

      # Step 4: Validate Terraform configurations
      - name: Validate Terraform
        run: terraform validate

      # Step 5: Plan Terraform changes
      - name: Terraform Plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: terraform plan

      # Step 6: Apply Terraform changes (on push only)
      - name: Apply Terraform
        if: github.event_name == 'push'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: terraform apply -auto-approve
