apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:your-org/k8s-manifests.git
    targetRevision: HEAD
    path: apps/react-app
  destination:
    server: https://kubernetes.default.svc
    namespace: react-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true