name: React App CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: my-cluster
  GKE_ZONE: us-central1-a
  IMAGE: react-app
  MANIFESTS_REPO: git@github.com:your-org/k8s-manifests.git

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test

  build-and-push:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io

      - name: Build Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA .
          docker build -t gcr.io/$PROJECT_ID/$IMAGE:latest .

      - name: Push Docker image
        run: |
          docker push gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
          docker push gcr.io/$PROJECT_ID/$IMAGE:latest

  update-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout manifests repo
        uses: actions/checkout@v3
        with:
          repository: your-org/k8s-manifests
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Update image tag in manifests
        run: |
          cd apps/react-app
          sed -i "s|gcr.io/$PROJECT_ID/$IMAGE:.*|gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA|" deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add apps/react-app/deployment.yaml
          git commit -m "Update image tag to $GITHUB_SHA"
          git push origin main